FROM node:20-alpine

WORKDIR /app

ENV NODE_OPTIONS="--max-old-space-size=3072"

COPY package*.json ./

RUN npm install

COPY . .

# Build-time environment variables required for Next.js
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY_ELEVATION
ARG NEXT_PUBLIC_API_BASE_URL=/api

ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY_ELEVATION=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY_ELEVATION
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NODE_ENV=production

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]